language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - android-24
    - sys-img-armeabi-v7a-android-24
    - extra-android-m2repository

  licenses:
    - android-sdk-license-c81a61d9
    - android-sdk-license-.+
    - google-gdk-license-.+

before_install:
  - chmod +x gradlew
  - echo $ANDROID_HOME
  - mkdir $ANDROID_HOME/licenses
  - echo 8933bad161af4178b1185d1a37fbf41ea5269c55 > $ANDROID_HOME/licenses/android-sdk-license

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - ./gradlew connectedCheck -PdisablePreDex --continue --info
  - ./gradlew test -PdisablePreDex --continue --info